### PR TITLE
refactor Scheme compiler to avoid pair/part -1

### PR DESCRIPTION
**Pull request by jamesdiacono**
What do you think?

### CODE REVIEW

**Comment by dalnefre** [comment]
It's a smaller change than I expected. What about the runtime cost though. The dedicated instructions are much faster.

**Comment by jamesdiacono** [comment]
It's true, but Scheme performance seems less important than an improved instruction set. If performance becomes a concern, we can modify the compiler to use the direct actor strategy ala the Humus compiler.

**Comment by dalnefre** [comment]
I hope we can use the "direct actor" strategy in any case, but I expect that would be a much larger change.

One feature of our Scheme that would require special treatment is the `(CALL `_actor_` `_args_`)` form.

**Comment by dalnefre** [comment]
`CALL` is used to make a pseudo-synchronous call to an "service" actor, where the implicit customer is the Scheme continuation. The value sent to the customer becomes the value of the `CALL` expression in the Scheme code. It's a convenient bridge between the sequential evaluation of Scheme expressions and the concurrent execution of Actors.

**Comment by jamesdiacono** [comment]
OK, I thought it was something like that.

**Pull request merged**
