### PR TITLE
Fault-tolerant assembler

### PR DESCRIPTION
**Pull request by jamesdiacono**
Once merged, you can try the improved syntax highlighting and linting at

https://ufork.org/playground/codejar.html?src=https://ufork.org/lib/cell.asm

Feedback on the syntax coloring is welcome.

### CODE REVIEW

**Comment by dalnefre** [comment]
I've committed an alternative color-scheme [#d2961d2](https://github.com/organix/uFork/commit/d2961d299c335cbaf93633505e53b67ffa9404a3) that looks similar to https://ufork.org/playground/monaco.html?src=https://ufork.org/lib/fork.asm

**Comment by jamesdiacono** [comment]
Should the namespaces have a different color to the labels? After all, you can't treat namespaces like labels. For example, you can't export a namespace.

**Comment by jamesdiacono** [comment]
Is it a requirement that the colors be websafe?

**Comment by dalnefre** [comment]
First, I would like to point out that this issue is subject to [bikeshedding](https://en.wiktionary.org/wiki/bikeshedding). Anything we discuss will be quite subjective. Still _some_ decision(s) must be made. Just remember that they're not nearly as important as many other aspects of this project.

That being said, what each of us has committed is a working-draft consolidating some of our recommendations. As usual, we'll benefit from a synthesis of our ideas. For example, I like the indirection you demonstrated with constructs like `var(--blue)`. That allows us to tweak the specific "blue" while keeping the same overall color-scheme.

I kept my proposal simple, trying to focus on the color-scheme more than the specific shades of color. The websafe (or named-color) palette is not required. It's just a simple place to start.

As for _namespaces_, I'm on the fence regarding their distinct treatment. For me, they are just another part of the _name_. So if there **is** a distinction, it should be minor. For example, I tried changing "white" to "pink" for _namespace_, which made is distinct yet sufficiently subtle. You'll notice that I don't use distinct colors for the various types of _literal_ (_string_, _number_, etc.) as I'm not sure it's important enough to use another color, even though they are distinct _types_.

On another note, would it make sense to create a separate style-sheet to define a "theme" or "skin"? If so, I would think that the syntactic category would be the key to selecting the color (and font style). Everything else could be common. The "theme" could employ of further indirection like `var(--blue)` to decouple the designation of specific shades.

**Comment by jamesdiacono** [comment]
How shall we converge on a color scheme? Our recommendations could not be more different. Introducing a theme feature does not really solve the problem, because then we must decide on a default theme, and besides, a theme feature seems premature at this point.

**Comment by jamesdiacono** [comment]
How shall we converge without excessive bikeshedding, I mean.

**Comment by dalnefre** [comment]
I view our proposals as simply starting points for discussion. Rather than focusing on the colors themselves, I think we can find common ground in the relationships between the colors and their semantic value.

How many colors do we need? One for each syntactic category, or can some categories share a color? Some categories have more similarities (or differences) than others. Comments, for example, should be clearly distinct from any "active" elements. Instructions (operators) are the most commons, so should be easy on the eyes. Literals are next, but they need to look good mixed in with the immediate keyword for instructions. Labels (names) are also mixed with operands, but should be distinct from literals.

The specific colors, or even the shades chosen, are less important than the visual balance and relationships between colors. Pulling them out into a "theme" just seems like an easy way to experiment and rapidly iterate.

**Comment by jamesdiacono** [comment]
Surprisingly, my text editor's color scheme uses only 7 colors, plus italics. I like the minimal palette because the colors are all very distinct.

I chose the categories with the view that they would each have a distinct style.

For example, I had intended that "data" and "terminal" operators be visually distinct,  because "data" operators can be chained whereas "terminal" operators can not be.
image

I think it's vital to be able to see at a glance where a statement stream ends:
image

I'm not keen on conflating strings with literals. Whilst strings can appear in expression position, they don't actually represent a textual value. Consider this confusing example:
image

 There is also the question of whether strings should take on a color reflecting their context. For example, namespace strings could take on the namespace color, and label strings could take on the label color.

**Comment by dalnefre** [comment]
You've made some excellent points, as I expected you would. I had forgotten that the quoted strings can be used for labels, not just import URLs. I would support using the _label_ color for strings. I still think _literal_ constants should be a different color than labels, and see no need to distinguish _numbers_ from symbolic names like `#nil`.

I already agreed that _namespaces_ could be either the same as _labels_, or a closely-related (but distinct) color. I also agree that terminal statements and branches should be clearly different from normal instructions (as they are in both our themes). I wasn't sure what to do with _data_, but I agree with your argument. It sounds like they should be the same (or at least similar) as chainable instruction _statements_. Maybe with _italic_ decoration.

I think the color-schemes are anchored by the choice of _operator_ color, which sets the tone for related _label_, _literal_, and _terminal_ colors. I object to your use of **red** for _operators_, which I feel should be reserved for errors. Even if it's not reserved, it's too little contrast for the most important element of the syntax.

My other objection is your choice of _comment_ color. I know you don't like comments with low contrast, but I don't want them to look like regular text, or any other element. Perhaps desaturation to a **medium-light-gray** would work, especially if nothing else is **white**. If we have to use **white**, then at least choose some color as visually-distant as possible from the main elements. I would prefer _not_ to use font-styles (like _italics_) for comments.

**Comment by jamesdiacono** [comment]
> You've made some excellent points, as I expected you would. I had forgotten that the quoted strings can be used for labels, not just import URLs. I would support using the label color for strings.
> 
I would also like to use the label color for strings used in label position, and the namespace color for strings used in namespace position, but only if it does not feel too weird to have the strings changing color as you type. I'll try it.
> I still think literal constants should be a different color than labels, and see no need to distinguish numbers from symbolic names like #nil.
> 
Agreed.
> I already agreed that namespaces could be either the same as labels, or a closely-related (but distinct) color.
> 
I'm OK with this so long as the label and namespace colors are easily distinguishable.
> I also agree that terminal statements and branches should be clearly different from normal instructions (as they are in both our themes). I wasn't sure what to do with data, but I agree with your argument. It sounds like they should be the same (or at least similar) as chainable instruction statements. Maybe with italic decoration.
> 
The most important distinction between data and instructions is that instructions may follow data, but data may not follow instructions.
> I think the color-schemes are anchored by the choice of operator color, which sets the tone for related label, literal, and terminal colors. I object to your use of red for operators, which I feel should be reserved for errors. Even if it's not reserved, it's too little contrast for the most important element of the syntax.
> 
How about blue?
> My other objection is your choice of comment color. I know you don't like comments with low contrast, but I don't want them to look like regular text, or any other element. Perhaps desaturation to a medium-light-gray would work, especially if nothing else is white. If we have to use white, then at least choose some color as visually-distant as possible from the main elements. I would prefer not to use font-styles (like italics) for comments.
> 
I don’t really mind what color we use for comments so long as it has excellent contrast. Comments are especially important in uFork assembly programs because of the stack diagrams. I found the green you chose to be unreadable on the dark background.

**Pull request merged**
