### PR TITLE
AWP device

### PR DESCRIPTION
**Pull request by jamesdiacono**

### CODE REVIEW

**Comment by dalnefre** [comment]
What do you think of adding a checkbox to enable loading the dev/debug build? It could be placed next to the "boot" controls in the GUI and persisted like the `boot-url`. I don't know how complicated it would be to re-load the WASM component on toggle. Maybe it could just force a page re-load after persisting the new setting?

**Comment by jamesdiacono** [comment]
I recently modified build.sh to build both the debug and release builds. That way, we can always run the debug build in the debugger, and still be notified of the size of the release build. Does that seem like a good solution?

**Comment by dalnefre** [comment]
That sounds reasonable, especially since both sizes were already being reported even if they weren't rebuilt. Did you also remove `dev-build.sh`, since it would be redundant (or misleading)?

**Comment by jamesdiacono** [comment]
I've removed it.

**Comment by dalnefre** [comment]
Can you extend this PR with the related changes, or is there a better way to get them integrated?

**Pull request merged**
