### PR TITLE
Minimise dependencies

### PR DESCRIPTION
**Pull request by jamesdiacono**
I had the pleasure of trying out the WASM browser demo yesterday, and it answered many of the questions I had about uFork's implementation. However, it took me a while to work out how to actually run it. This is my attempt at de-template-ifying the ufork-wasm directory, making it easier to explore and use.

---

The WASM demo was built using Webpack, which has about 450 subdependencies and does not even work with newer versions of Node.js. This commit simplifies things by removing Webpack, which turned out to be unnecessary anyway.

As part of the simplification, I had to remove the Conway's Game of Life stuff, which, until I realised it just was the remnant of a tutorial, made the demo quite confusing.

### CODE REVIEW

**Comment by dalnefre** [comment]
I'm excited about this contribution and thank you for your effort. I generally prefer a minimalist approach, so reducing dependencies is definitely attractive.

What I'm less excited about is the timing of introducing these changes. I'm in the midst of a series of systemic refactorings that effect the entire architecture. Since this has been primarily a solo project, I haven't laid out a roadmap to communicate my intentions (my bad). I'd like to find the best way to integrate your work without disruption.

As you've likely noticed, the WASM foundation and hosting web-page are derived from a [tutorial](https://rustwasm.github.io/docs/book/game-of-life/introduction.html) in which Conway's Game of Life is the visible part of the functional demonstration. I've kept the Life demo as part of the uFork GUI for a few reasons. To demonstrate concurrency, as an indication of activity (when the VM might be stuck), and as reference code for interaction between WASM and JavaScript. I'd like to keep it around a little longer, if possible, so I'd like to understand what dependencies it requires that will not also be need by uFork (eventually).

I feel bad about the current state of disarray in uFork. It must be difficult to try and make contributions to a rapidly evolving project. Your effort is appreciated. I would love to trim down the dependencies, and don't have the knowledge to do it myself. But I would prefer to give you a more stable foundation on which to do your work.

I haven't even written a "Getting Started" guide so curious folks like yourself would know where to start. Selecting various demo scenarios is current accomplished through changes in the code, which is certainly not acceptable for anyone other than an author. Some of the planned architectural changes include mechanisms to load various VM images, which would be a much more friendly way of managing configurations...

**Comment by dalnefre** [comment]
I've review the diffs and I really like the idea of removing the baggage associated with the webpack template. However, I'd like to retain the game-of-life demo (as an example of direct `memory` access), and the console logging mechanism (if possible).

I also like the simple node.js-based webserver. I think the web assets should remain isolated in the `www` subdirectory, and thus the webserver should use `www` as its webroot. It looks like that would be a relatively minor adjustment. Also leaving `index.html` as the default document seems more normal to me.

I've reached a point of stability, having completed the refactoring from `Typed`/`Val` to `Quad`/`Any`, so you should be able to rebase and make the merge easy. Thanks again for your effort!

**Comment by jamesdiacono** [comment]
That all sounds possible and good, I'll get on it.

**Comment by diachedelic** [comment]
I've made the suggested changes, but I kept the "ufork-wasm" directory as the webroot because otherwise index.js is not able to access the "pkg" directory. To make "www" the webroot, we would have to either symlink "pkg" into "www", or copy it over as part of the build step.

**Comment by jamesdiacono** [comment]
I've made the suggested changes, but I kept the "ufork-wasm" directory as the webroot because otherwise index.js is not able to access the "pkg" directory. To make "www" the webroot, we would have to either symlink "pkg" into "www", or copy it over as part of the build step.

**Pull request merged**
