### PR TITLE
SVG device

### PR DESCRIPTION
**Pull request by jamesdiacono**
This adds all the plumbing for displaying an SVG in the playground, you just need to handle the messages in svg_dev.js.

### CODE REVIEW

**Comment by jamesdiacono** [comment]
Once merged, you can run this demo: https://ufork.org/playground?text=H4sIAAAAAAAAE3XQwQ6CMAwG4PueouGkB4fADfTsA5h4JcDKIDhG1rFojO9uGMTEgL32y5/+zeB6u4BA11YIApXmjPFWDdpYBgDTJoWgsXagNAzHWpuOayPDe1uGAh0vSAUekhV/IVkxQ1ZqbVNYTwa7PZwO8KqKgd4+cBipgShOflmllSp6cY7ixCtFEo6rsEWt4qaLycm8w+cWhGU3N28rCxLtdjI56ZXBeqrOCXuRK5KMcXx8vzfVZR/kmcBXYwEAAA%3D%3D&device=svg

**Comment by dalnefre** [comment]
This is great! Thanks for establishing the infrastructure.

One small thing. Since you just renamed everything from "device" to "dev", why isn't the query parameter "dev"?

**Comment by jamesdiacono** [comment]
Good point, I will change it.

**Comment by jamesdiacono** [comment]
Shouldn't there be a wire command to set the background, rather than a picker?

**Comment by jamesdiacono** [comment]
After all, the background will strongly influence what colors should be chosen by the uFork program.

**Comment by dalnefre** [comment]
The background and range of coordinates are both set by the SVG element context, not by the drawing code. I'd like to add a "scale" slider as well to set the viewport coordinate range. These are generally outside the control of the "program", but allowing the playground to be adjustable lets us run code in useful variety of contexts.

**Comment by jamesdiacono** [comment]
That makes sense for the viewBox, but I don't think it makes sense for the background. If the program wants a non-white background it could just draw a big square and fill it in, right?

**Comment by dalnefre** [comment]
An SVG is a transparent sheet on which we place opaque (by default) ink. There is no "background" color. Take, for example, the [uFork logo](https://ufork.org/ufork_logo.svg). We may want to see how a drawing appears on a variety of backgrounds. And, yes, if a drawing wants/needs a specific background, it just includes a simple filled rectangle.

**Comment by jamesdiacono** [comment]
Yeah, I guess that makes sense.

**Pull request merged**
