### PR TITLE
playground line numbering

### PR DESCRIPTION
**Pull request by jamesdiacono**

### CODE REVIEW

**Comment by dalnefre** [comment]
Trying to share a simple ["Hello, World!"](https://ufork.org/playground/?text=OyBBIHNpbXBsZSAiSGVsbG8sIFdvcmxkISIgZXhhbXBsZQoKLmltcG9ydAogICAgZGV2OiAiaHR0cHM6Ly91Zm9yay5vcmcvbGliL2Rldi5hc20iCgpoZWxsbzogICAgICAgICAgICAgICAgICA7ICgrNzIgKzEwMSArMTA4ICsxMDggKzExMSArNjMgKzEwKQogICAgcGFpcl90ICdIJwogICAgcGFpcl90ICdlJwogICAgcGFpcl90ICdsJwogICAgcGFpcl90ICdsJwogICAgcGFpcl90ICdvJwogICAgcGFpcl90ICc%2FJwogICAgcGFpcl90ICdcbicKICAgIHJlZiAjbmlsCgpib290OiAgICAgICAgICAgICAgICAgICA7ICgpIDwtIHtjYXBzfQogICAgcHVzaCBoZWxsbyAgICAgICAgICA7IHZhbHVlCiAgICBtc2cgMCAgICAgICAgICAgICAgIDsgLi4uIHtjYXBzfQogICAgcHVzaCBkZXYuZGVidWdfa2V5ICA7IC4uLiB7Y2Fwc30gZGV2LmRlYnVnX2tleQogICAgZGljdCBnZXQgICAgICAgICAgICA7IHZhbHVlIGRlYnVnX2Rldgo7ICAgIG1zZyAwICAgICAgICAgICAgICAgOyAuLi4ge2NhcHN9CjsgICAgcHVzaCBkZXYuY2xvY2tfa2V5ICA7IC4uLiB7Y2Fwc30gZGV2LmNsb2NrX2tleQo7ICAgIGRpY3QgZ2V0ICAgICAgICAgICAgOyBjdXN0IGNsb2NrX2RldgogICAgc2VuZCAtMSAgICAgICAgICAgICA7IC0tCiAgICBlbmQgY29tbWl0CgouZXhwb3J0CiAgICBib290Cgo%3D) example. It looks line line-breaks are broken, and I don't see any line numbers.

image

**Comment by dalnefre** [comment]
When there are more than 100 lines, it looks like the numbers wrap and leave a gap at the end.
For example [https://ufork.org/playground/?file=https://ufork.org/debugger/examples/e_ring.asm](https://ufork.org/playground/?file=https://ufork.org/debugger/examples/e_ring.asm)

image

**Comment by jamesdiacono** [comment]
Oops, fixed

**Comment by dalnefre** [comment]
There also appears to be an unreachable extra line at the end of the file/buffer.

**Pull request merged**
