### PR TITLE
Embed editor state in URL

### PR DESCRIPTION
**Pull request by jamesdiacono**
There is now a button that runs the code:

https://ufork.org/playground/?file=https://ufork.org/lib/future.asm

Changes to the text in the playground's editor are now reflected in the URL, making it trivial to share programs via a link. For example:

https://ufork.org/playground/?text=OyB1Rm9yayBIZWxsbyBXb3JsZAoKLmltcG9ydAogICAgc3RkOiAiaHR0cHM6Ly91Zm9yay5vcmcvbGliL3N0ZC5hc20iCiAgICBkZXY6ICJodHRwczovL3Vmb3JrLm9yZy9saWIvZGV2LmFzbSIKCm1lc3NhZ2U6CiAgICBwYWlyX3QgJ0gnCiAgICBwYWlyX3QgJ2UnCiAgICBwYWlyX3QgJ2wnCiAgICBwYWlyX3QgJ2wnCiAgICBwYWlyX3QgJ28nCiAgICBwYWlyX3QgJywnCiAgICBwYWlyX3QgJyAnCiAgICBwYWlyX3QgJ1cnCiAgICBwYWlyX3QgJ28nCiAgICBwYWlyX3QgJ3InCiAgICBwYWlyX3QgJ2wnCiAgICBwYWlyX3QgJ2QnCiAgICBwYWlyX3QgJyEnCiAgICByZWYgI25pbAoKYm9vdDogICAgICAgICAgICAgICAgICAgICAgIDsgKCkgPC0ge2NhcHN9CiAgICBwdXNoIG1lc3NhZ2UgICAgICAgICAgICA7IG1lc3NhZ2UKICAgIG1zZyAwICAgICAgICAgICAgICAgICAgIDsgbWVzc2FnZSB7Y2Fwc30KICAgIHB1c2ggZGV2LmRlYnVnX2tleSAgICAgIDsgbWVzc2FnZSB7Y2Fwc30gZGVidWdfa2V5CiAgICBkaWN0IGdldCAgICAgICAgICAgICAgICA7IG1lc3NhZ2UgZGVidWcKICAgIHJlZiBzdGQuc2VuZF9tc2cKCi5leHBvcnQKICAgIGJvb3QKCg%3D%3D

### CODE REVIEW

**Comment by dalnefre** [comment]
What do you think of compressing the text before encoding the binary form? It seems like it should compress very well, and that would keep the URLs shorter.

**Comment by jamesdiacono** [comment]
There is a way to compress a bytestream gzip without pulling in a library, but it’s pretty bleeding edge. It’s only available in iOS 16.4+, for example.

https://developer.mozilla.org/en-US/docs/Web/API/CompressionStream

My feeling is that the URLs are going to look horrendous whatever we do. If we want pretty URLs we are going to need centralized storage.

**Comment by dalnefre** [comment]
According to the docs you linked, there has been wide support for 1-3 years. How is this "bleeding edge"? It seems like "gzip" is the most widely supported format, and should be auto-detectable due to the header signature.

I'm not worried about pretty, just *big*. When I tried to share the "Hello, World!" example in text-chat, it got truncated, and that's not a very big example.

**Comment by jamesdiacono** [comment]
It’s bleeding edge in that many phones, such as my iPhone, do not support it. The latest version of iOS is 17.3, this feature requires 16.4. If we are happy to target only the latest versions of browsers that would make my job easier, but it would make the playground links less universal.

**Comment by jamesdiacono** [comment]
Makes sense to me. I’ll look into it.

**Pull request merged**
